shortener/urls.py
from django.conf.urls import url, include
from . import views

app_name = 'shortener'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<short_id>\w+)$', views.redirect_original, name='redirect')
]

url_shortener/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('shortener.urls')),
]

shortener/models.py
from django.db import models
from .code_generator import code_generator
# Create your models here.


class ShortURL(models.Model):
    url = models.URLField(unique=True)
    code = models.CharField(max_length=7, null=True, unique=True, blank=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.url

    def save(self, *args, **kwargs):
        self.code = code_generator()
        super(ShortURL, self).save(*args, **kwargs)

shortener/forms.py
from django import forms
from .models import ShortURL

class ShortURLForm(forms.ModelForm):
    class Meta:
        model = ShortURL
        fields = ['url']

shortener/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .forms import ShortURLForm
from url_shortener.settings import LOCAL_HOST
from .models import ShortURL

# Create your views here.
def index(request):
    form = ShortURLForm(request.POST or None)
    code = ''
    if form.is_valid():
        data = form.save(commit=False)
        url = form.cleaned_data['url']
        data.save()
        dataset = ShortURL.objects.filter(url=url)
        code = dataset[0].code
        short_url = LOCAL_HOST + '/' + code
        return render(request, 'shortener/index.html', {'form':form, 'short_url':short_url, 'code':code})
    else:
        return render(request, 'shortener/index.html', {'form':form, 'code':code})

def redirect_original(request, short_id):
    url = get_object_or_404(ShortURL, code=short_id)
    return redirect(str(url))

shortener/templates/shortener/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
    {% block head %}{% endblock %}
</head>
<body>
{% block body %}{% endblock %}
</body>
</html>

shortener/templates/shortener/index.html
{% extends 'shortener/base.html' %}
{% load bootstrap3 %}
{% block title %}URLShortener{% endblock %}
{% block head %}
    <style>
        h1{
            color: cornflowerblue;
        }
        *{
            margin: 5px;
            padding: 5px;
        }

    </style>
{% endblock %}
{% block body %}
    <h1>WELCOME TO URL SHORTENER</h1>
    <h4>Shorten your URL</h4>
    <form method="post" action="{% url 'shortener:index' %}" class="form-inline">
        {% csrf_token %}
    {% bootstrap_form_errors form type='non_fields' %}
    {% bootstrap_form form layout='inline' %}

    {% buttons %}
        <button type="submit" class="btn btn-primary" style="cursor: pointer">Submit</button>
    {% endbuttons %}
    </form>
    {% if code %}
    <h3>Link Generated:</h3>
    <a href="{% url 'shortener:redirect' short_id=code %}" >{{ short_url }}</a>
    {% endif %}
{% endblock %}